name: Plan

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: plan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    name: Config Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_version: '1.12.5'

      - name: Initialize
        run: tofu init -input=false

      - name: Validate
        run: tofu validate

      - name: Check formatting
        run: tofu fmt -check -recursive

      - name: Plan
        shell: bash
        env:
          GITHUB_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.VALKYRJA_GHA_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
        run: |
          tofu plan -input=false -no-color 2>&1 | tee plan.txt
          {
            echo '## OpenTofu plan'
            echo '```'
            tail -n 200 plan.txt
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
